### ISSUE TITLE
ES6 Refactor (v0.11.0 Release Checklist)

### ISSUE THREAD

**Issue by bpatram** [PaulUithol/Backbone-relational#572]
I've started work on refactoring some of bbr to use Rollup + Babel with a more modular design. Overall this should help everyone out to make it more extensible and easier to maintain in the long run. All work will be done on the `next` branch, if you are submitting a pull request make sure to branch off `next` until the release is completed.

- [x] Export in separate namespace #566
- [x] Create rollup configuration
- [x] Create `prepublish` npm script task to run rollup
- [ ] Move into separate modules:
  - [x] `Relation`
    - [x] Decouple `Relation` from `HasOne` and `HasMany` (create lookup store for relation types)
  - [ ] `HasOne`
  - [ ] `HasMany`
  - [x] `Collection`
  - [x] `Model`
  - [x] `Store`
  - [x] `Semaphore`
- [x] Create base object extensible object
  - [x] Refactor `Relation` to use base object
  - [x] Refactor `Store` to use base object
- [x] Refactor test setup to use distributable
- [ ] Ensure all unit tests pass
- [ ] Update documentation #567 
- [ ] Create upgrade guide
- [ ] Update contribution guidelines
- [ ] Create [PR](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) and [Issue templates](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) for github
- [ ] Create shimmed distributable to export how `v0.10.0` does to ease transition
- [ ] Update TravisCI tests to test against multiple Backbone versions

Since This library is so tightly coupled in places there will be more extensive refactoring required (for example, the base `Relation` 'class' is dependent on `HasOne` and `HasMany` while both `HasOne` and `HasMany` extend and depend on `Relation`).

Due to the nature of this large of a refactor I'm unsure how collaboration will work out with PRs and merge conflicts. It will take extra coordination.

**Comment by bpatram** [comment]
What I ended up adding is a relation type store, which maps the relation types to their names. 'HasMany' => Relation.HasMany and the same idea for HasOne. This would also make it easier to override and register new relation types (Many to many?) in the future.
